
-- Create Robotics & Automation category
INSERT INTO public.marketplace_categories (id, name, description, icon, is_active)
VALUES ('a1b2c3d4-5678-9abc-def0-111111111111', 'Robotics & Automation', 'Industrial robotics platforms, simulation tools, and automation solutions', 'bot', true)
ON CONFLICT (id) DO NOTHING;

-- Insert 20 Robotics tools under @DIM_Earn account
INSERT INTO public.marketplace_listings (user_id, category_id, title, description, listing_type, status, currency, tags, creation_link, pricing_tiers) VALUES

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Universal Robots',
'The world''s leading collaborative robot (cobot) manufacturer. Universal Robots makes flexible, safe, and easy-to-program robotic arms (UR3e, UR5e, UR10e, UR16e, UR20, UR30) designed to work alongside humans. Ideal for pick-and-place, machine tending, assembly, welding, palletizing, and quality inspection across industries.',
'product', 'active', 'USD',
ARRAY['robotics','cobots','automation','manufacturing','industrial'],
'https://www.universal-robots.com/',
'[{"name":"UR3e","price":25000,"period":"one-time","features":["3kg payload","500mm reach","Tabletop cobot","Easy programming"]},{"name":"UR5e","price":35000,"period":"one-time","features":["5kg payload","850mm reach","Versatile mid-range","Force/torque sensing"]},{"name":"UR10e","price":45000,"period":"one-time","features":["12.5kg payload","1300mm reach","Heavy-duty tasks","Built-in safety"]},{"name":"UR20","price":55000,"period":"one-time","features":["20kg payload","1750mm reach","Next-gen cobot","High performance"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'AWS RoboMaker',
'Amazon''s cloud robotics service for developing, simulating, and deploying intelligent robotics applications at scale. Integrates with ROS and provides managed simulation environments, fleet management, and over-the-air deployment. Note: Discontinued in 2025 but remains influential in cloud robotics architecture.',
'product', 'active', 'USD',
ARRAY['robotics','cloud','aws','simulation','ROS'],
'https://aws.amazon.com/robomaker/',
'[{"name":"Free Tier","price":0,"period":"forever","features":["25 SU hours/month","ROS integration","Basic fleet management"]},{"name":"Pay-As-You-Go","price":0,"period":"monthly","features":["Per simulation unit hour","Scalable compute","CloudWatch integration"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'NVIDIA Isaac Sim',
'NVIDIA''s powerful robotics simulation platform built on Omniverse. Enables photorealistic, physically-accurate 3D simulation for training and testing AI-powered robots. Features synthetic data generation, domain randomization, ROS/ROS2 integration, and GPU-accelerated physics.',
'product', 'active', 'USD',
ARRAY['robotics','simulation','nvidia','AI','deep-learning','omniverse'],
'https://developer.nvidia.com/isaac/',
'[{"name":"Free","price":0,"period":"forever","features":["Isaac Sim access","ROS2 integration","Synthetic data generation","Community support"]},{"name":"Enterprise","price":0,"period":"monthly","features":["Priority support","Enterprise deployment","Custom integrations"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'RobotShop',
'The world''s leading online retailer for personal and professional robot technology. Offers thousands of robotics products including robot kits, drones, sensors, actuators, development boards, and accessories for hobbyists, educators, researchers, and professionals.',
'product', 'active', 'USD',
ARRAY['robotics','marketplace','hardware','sensors','kits','education'],
'https://www.robotshop.com/',
'[{"name":"Marketplace","price":0,"period":"forever","features":["Browse 5000+ products","Free shipping on $75+","Expert reviews","Educational resources"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Autodesk Fusion 360',
'Powerful cloud-based 3D CAD, CAM, CAE, and PCB software for product design and manufacturing. Combines industrial design, mechanical engineering, simulation, and collaboration in one platform. Widely used for designing robotic components, enclosures, and mechanical assemblies.',
'product', 'active', 'USD',
ARRAY['CAD','3D-design','manufacturing','engineering','simulation','PCB'],
'https://www.autodesk.com/products/fusion-360/overview',
'[{"name":"Personal","price":0,"period":"forever","features":["Non-commercial use","Basic CAD/CAM","10 active documents"]},{"name":"Standard","price":70,"period":"monthly","features":["Full CAD/CAM/CAE","Unlimited documents","Generative design"]},{"name":"Team","price":100,"period":"monthly","features":["Everything in Standard","Team collaboration","Admin controls"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Robot Operating System (ROS)',
'The industry-standard open-source framework for robot software development. ROS provides libraries and tools for building robot applications — from drivers and perception to navigation and manipulation. ROS 2 brings real-time performance, security, and multi-platform support.',
'product', 'active', 'USD',
ARRAY['robotics','open-source','framework','ROS2','middleware','navigation'],
'https://www.ros.org/',
'[{"name":"Open Source","price":0,"period":"forever","features":["Full framework access","Extensive package ecosystem","Multi-language support","Active community"]},{"name":"ROS 2","price":0,"period":"forever","features":["Real-time capable","DDS middleware","Security features","Multi-platform"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'ABB Robotics',
'Global leader in industrial robotics and automation. ABB offers a comprehensive range of industrial robots, cobots (GoFa, SWIFTI), and RobotStudio software for manufacturing, logistics, and process automation. Known for precision, reliability, and advanced motion control.',
'product', 'active', 'USD',
ARRAY['robotics','industrial','automation','manufacturing','cobots'],
'https://new.abb.com/products/robotics',
'[{"name":"RobotStudio Free","price":0,"period":"forever","features":["Offline programming","Virtual commissioning","Basic simulation"]},{"name":"RobotStudio Premium","price":150,"period":"monthly","features":["Multi-robot simulation","VR support","Advanced path planning"]},{"name":"Industrial Robots","price":0,"period":"one-time","features":["Custom configurations","Contact sales","24/7 service"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'KUKA Robotics',
'German manufacturer of industrial robots and automation solutions. KUKA provides robots for welding, palletizing, handling, and assembly with payloads from 3kg to 1300kg. Their KUKA.Sim software and KSS power intelligent automation in automotive, aerospace, and healthcare.',
'product', 'active', 'USD',
ARRAY['robotics','industrial','automation','welding','palletizing'],
'https://www.kuka.com/',
'[{"name":"KUKA.Sim Basic","price":0,"period":"forever","features":["Basic simulation","Layout planning","Robot selection"]},{"name":"KUKA.Sim Pro","price":200,"period":"monthly","features":["Full simulation","Offline programming","PLC connectivity"]},{"name":"Industrial Robots","price":0,"period":"one-time","features":["3-1300kg payload range","Custom solutions","Global support"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Fetch Robotics (Zebra)',
'Autonomous mobile robots (AMRs) for warehouse and logistics automation, now part of Zebra Technologies. Cloud-managed robots for material transport, data collection, and warehouse operations. FetchCore platform enables fleet management and real-time analytics.',
'product', 'active', 'USD',
ARRAY['robotics','AMR','warehouse','logistics','automation','fleet-management'],
'https://www.zebra.com/us/en/products/mobile-robots.html',
'[{"name":"FetchCore Cloud","price":0,"period":"monthly","features":["Fleet management","Workflow orchestration","Real-time analytics","Contact sales"]},{"name":"Enterprise","price":0,"period":"monthly","features":["Multi-site management","Custom integrations","Priority support"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'RoboDK',
'Powerful and cost-effective robot simulation and offline programming software. Supports 800+ robot models from 70+ manufacturers with automatic vendor-specific program generation. Features 3D simulation, collision detection, and path optimization.',
'product', 'active', 'USD',
ARRAY['robotics','simulation','offline-programming','CAD','industrial'],
'https://robodk.com/',
'[{"name":"Trial","price":0,"period":"forever","features":["30-day full access","50-instruction limit after","Unlimited robot library"]},{"name":"Professional","price":3995,"period":"one-time","features":["Full simulation","Offline programming","500+ post-processors"]},{"name":"Enterprise","price":7995,"period":"one-time","features":["Multi-robot cells","API access","Custom post-processors"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Clearpath Robotics',
'Leading provider of autonomous mobile robots for research and industrial applications. Builds rugged, ROS-based platforms (Husky, Jackal, Warthog, Dingo) designed for outdoor navigation, inspection, agriculture, mining, and defense applications.',
'product', 'active', 'USD',
ARRAY['robotics','mobile-robots','research','ROS','autonomous','outdoor'],
'https://clearpathrobotics.com/',
'[{"name":"Dingo","price":15000,"period":"one-time","features":["Indoor mobile robot","Compact form factor","ROS integration"]},{"name":"Jackal","price":20000,"period":"one-time","features":["All-terrain UGV","Weatherproof","GPS/IMU navigation"]},{"name":"Husky","price":30000,"period":"one-time","features":["Large payload","Rugged outdoor","Autonomous navigation"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'SolidWorks',
'Industry-leading 3D CAD software by Dassault Systèmes for mechanical design and engineering. Provides parametric modeling, simulation (FEA, CFD), and product data management essential for designing robotic components, mechanisms, and complete systems.',
'product', 'active', 'USD',
ARRAY['CAD','3D-modeling','engineering','simulation','manufacturing'],
'https://www.solidworks.com/',
'[{"name":"Standard","price":3995,"period":"one-time","features":["3D CAD modeling","2D drawings","Basic simulation"]},{"name":"Professional","price":5490,"period":"one-time","features":["Advanced simulation","Routing","Toolbox library"]},{"name":"Premium","price":7995,"period":"one-time","features":["FEA/CFD analysis","Tolerance analysis","Sustainability tools"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'MathWorks MATLAB & Simulink',
'Essential computing platform for robotics algorithm development, simulation, and deployment. MATLAB provides powerful mathematical computing while Simulink enables model-based design for control systems. Robotics, ROS, and Navigation Toolboxes included.',
'product', 'active', 'USD',
ARRAY['MATLAB','Simulink','robotics','control-systems','simulation'],
'https://www.mathworks.com/',
'[{"name":"Student","price":49,"period":"one-time","features":["MATLAB base","Limited toolboxes","Academic use only"]},{"name":"Standard","price":940,"period":"yearly","features":["Full MATLAB","Add-on toolboxes","Commercial use"]},{"name":"Enterprise","price":0,"period":"yearly","features":["Volume licensing","Custom deployment","Contact sales"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Energid Actin SDK',
'Advanced robot control and motion planning software. Actin SDK provides real-time adaptive motion control, collision avoidance, and multi-robot coordination. Acquired by Universal Robots, powers sophisticated manipulation in manufacturing, medical, and space applications.',
'product', 'active', 'USD',
ARRAY['robotics','motion-planning','control','SDK','manipulation'],
'https://www.energid.com/',
'[{"name":"Actin SDK","price":0,"period":"one-time","features":["Real-time motion planning","Collision avoidance","Multi-robot coordination","Contact sales"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Webots',
'Free and open-source 3D robot simulator by Cyberbotics. Provides a complete development environment for modeling, programming, and simulating robots with realistic physics. Supports C, C++, Python, Java, MATLAB, and ROS integration.',
'product', 'active', 'USD',
ARRAY['robotics','simulation','open-source','education','research','ROS'],
'https://cyberbotics.com/',
'[{"name":"Open Source","price":0,"period":"forever","features":["Full simulator","Physics engine (ODE)","Multi-language API","ROS/ROS2 integration"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'OnRobot',
'Leading manufacturer of end-of-arm tooling (EOAT) for collaborative and industrial robots. Offers grippers, sensors, tool changers, and screwdrivers that integrate seamlessly with all major robot brands for pick-and-place, assembly, and quality inspection.',
'product', 'active', 'USD',
ARRAY['robotics','grippers','end-effectors','cobots','tooling'],
'https://onrobot.com/',
'[{"name":"Grippers","price":3000,"period":"one-time","features":["Plug-and-play","Multi-robot compatible","Flexible gripping"]},{"name":"Sensors","price":5000,"period":"one-time","features":["Force/torque sensing","Proximity detection","Real-time feedback"]},{"name":"Complete Kits","price":8000,"period":"one-time","features":["Gripper + sensor bundle","Quick deployment","Training included"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Formlabs',
'Professional 3D printing solutions for rapid prototyping and production. Industry-leading SLA and SLS printers (Form 4, Fuse 1+) with engineering-grade resins. Essential for robotics teams prototyping custom parts, enclosures, and grippers.',
'product', 'active', 'USD',
ARRAY['3D-printing','prototyping','manufacturing','SLA','SLS'],
'https://formlabs.com/',
'[{"name":"Form 4","price":3999,"period":"one-time","features":["SLA 3D printer","Fast print speeds","200+ micron accuracy"]},{"name":"Form 4L","price":9999,"period":"one-time","features":["Large format SLA","5x build volume","Production-grade"]},{"name":"Fuse 1+ 30W","price":27999,"period":"one-time","features":["SLS 3D printer","Nylon/TPU materials","Industrial quality"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Siemens NX',
'Enterprise-grade integrated CAD/CAM/CAE solution for advanced product engineering. Provides parametric modeling, generative design, multiphysics simulation, and manufacturing automation for designing complex mechatronic systems and robotic cells.',
'product', 'active', 'USD',
ARRAY['CAD','CAM','CAE','engineering','simulation','enterprise'],
'https://plm.sw.siemens.com/en-US/nx/',
'[{"name":"Standard","price":0,"period":"yearly","features":["Full CAD/CAM/CAE","Generative design","Cloud collaboration","Contact sales"]},{"name":"Enterprise","price":0,"period":"yearly","features":["Multi-discipline design","Advanced simulation","PLM integration"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Rethink Robotics',
'Pioneer of collaborative robotics, known for Baxter and Sawyer cobots that popularized human-robot collaboration. Introduced intuitive teach-by-demonstration programming and embedded vision. Though the original company closed, their technology continues to influence the cobot industry.',
'product', 'active', 'USD',
ARRAY['robotics','cobots','collaborative','manufacturing','legacy'],
'https://rethinkrobotics.com/',
'[{"name":"Legacy Platform","price":0,"period":"one-time","features":["Baxter/Sawyer ecosystem","Intera SDK","Research community","Contact for availability"]}]'::jsonb),

('fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'a1b2c3d4-5678-9abc-def0-111111111111',
'Neura Robotics',
'Next-generation cognitive robotics company building the world''s first cognitive cobot (MAiRA). Combines AI, sensor fusion, and advanced mechanics to create robots that can see, hear, and feel their environment. LARA and MAiRA platforms bring human-like perception to industrial automation.',
'product', 'active', 'USD',
ARRAY['robotics','cognitive','AI','cobots','sensors','next-gen'],
'https://neura-robotics.com/',
'[{"name":"LARA","price":0,"period":"one-time","features":["Lightweight cobot","High precision","Easy programming","Contact sales"]},{"name":"MAiRA","price":0,"period":"one-time","features":["Cognitive cobot","AI-powered perception","Voice/gesture control","Contact sales"]}]'::jsonb);
