
-- 1. Gebeya Dala
INSERT INTO marketplace_listings (title, description, listing_type, user_id, status, category_id, tags, creation_link, pricing_tiers) VALUES
('Gebeya Dala', 'Africa''s no-code AI app builder that generates full-stack websites, apps, games, and comics from natural language prompts in African languages like Amharic, Swahili, Oromifa, French, and Arabic. Optimized for mobile and low-data environments.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['no-code','app-builder','african-languages','ethiopia'], 'https://gebeya.com/dala/', '[{"name":"Free","price":0,"period":"forever","features":["Build apps & websites","Multilingual AI prompts","Mobile-optimized","Community templates"]},{"name":"Pro","price":0,"period":"monthly","features":["Contact Gebeya for pricing","Custom domains","Priority builds","Commercial license"]}]'::jsonb),
-- 2. Curation AI
('Curation AI', 'The #1 AI tool for content verification, authentication, and opinion insights. Detects AI-generated media, deepfakes, and manipulated content across videos, images, text, audio, and documents in real-time.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['deepfake-detection','content-verification','nigeria'], 'https://www.curationai.ai/', '[{"name":"Free Trial","price":0,"period":"forever","features":["Basic verification","Limited scans","Web interface","Community support"]},{"name":"Professional","price":0,"period":"monthly","features":["Contact sales","Unlimited scans","API access","Real-time monitoring"]}]'::jsonb),
-- 3. YarnGPT
('YarnGPT', 'Nigerian-built multilingual AI for text-to-speech, video dubbing, and voiceovers. Synthesizes natural-sounding speech in Nigerian-accented English and local languages including Yoruba, Igbo, and Hausa. Pay-as-you-go with no subscriptions.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['text-to-speech','voice-ai','nigerian-languages','dubbing'], 'https://yarngpt.ai/', '[{"name":"Pay-As-You-Go","price":0,"period":"forever","features":["No subscription","Pay per generation","All Nigerian languages","Natural voices"]}]'::jsonb),
-- 4. YesCheff
('YesCheff', 'Interactive AI kitchen assistant that transcribes cooking videos into structured recipes with timers, ingredient lists, and shopping suggestions. Learns your preferences for personalized cooking guidance.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['cooking-ai','recipe-generator','nigeria','meal-planning'], 'https://www.yeschefai.com/', '[{"name":"Basic (Free)","price":0,"period":"forever","features":["Menu creation","Shopping lists","Limited AI bot","Cooking instructions"]},{"name":"Standard","price":15,"period":"monthly","features":["Full AI bot access","Learns preferences","Online ordering","Save menus"]},{"name":"Premium","price":30,"period":"monthly","features":["Everything in Standard","Upload recipes","Share with friends","Priority support"]}]'::jsonb),
-- 5. JobPilot AI
('JobPilot AI', 'AI-powered career tool from Ghana for job matching, resume building, interview simulation, and professional networking. Uses AI to match candidates with opportunities and prepare for interviews.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['career-ai','resume-builder','interview-prep','ghana'], 'https://jobpilot.faylab.com/', '[{"name":"Free","price":0,"period":"forever","features":["Basic job search","1 resume","Limited AI matching","Community access"]},{"name":"Pro","price":0,"period":"monthly","features":["Contact for pricing","Unlimited resumes","AI interviews","Premium matching"]}]'::jsonb),
-- 6. SmartSkin Africa
('SmartSkin Africa', 'AI skincare analysis platform for African skin types. Snap a 3-second selfie for real-time AI diagnostics, personalized product recommendations, and skin tracking. Designed for melanin-rich skin.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['skincare-ai','beauty-tech','african-skin','ghana'], 'https://smartskinafrica.com/', '[{"name":"Free Analysis","price":0,"period":"forever","features":["AI skin diagnostic","Basic recommendations","Selfie analysis","Skin type detection"]},{"name":"Premium","price":0,"period":"monthly","features":["Contact for pricing","Advanced tracking","Personalized routines","Product recommendations"]}]'::jsonb),
-- 7. Thunders
('Thunders', 'AI-native software testing platform from Tunisia. Generates automated tests from plain English. Founded by the InstaDeep team ($682M exit). Boosts QA efficiency by 90%. Backed by $9M seed funding.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['software-testing','qa-automation','tunisia','ai-testing'], 'https://www.thunders.ai/', '[{"name":"Starter","price":399,"period":"monthly","features":["300 credits (30K test steps)","1-2 users","AI test generation","Community support"]},{"name":"Pro","price":999,"period":"monthly","features":["1,000 credits","Up to 10 users","Full persona catalog","90-day storage"]},{"name":"Enterprise","price":0,"period":"monthly","features":["Contact sales","Unlimited users","SSO & integrations","Dedicated manager"]}]'::jsonb),
-- 8. Xara
('Xara', 'Africa''s first AI financial assistant on WhatsApp. Send money, check balances, and manage finances across 50+ Nigerian banks using natural language, voice, or images in local dialects. Powered by GPT-4.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['fintech','whatsapp-banking','ai-finance','nigeria'], 'https://usexara.ai/', '[{"name":"Free","price":0,"period":"forever","features":["WhatsApp banking","Natural language transactions","50+ banks","Voice & image commands"]}]'::jsonb),
-- 9. Chidi
('Chidi', 'AI learning companion built on Anthropic''s Claude, launched by ALX, Anthropic, and the Government of Rwanda. Uses Socratic methods for critical thinking through interactive lessons.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['edtech','ai-tutor','socratic-learning','rwanda'], 'https://www.alxafrica.com/', '[{"name":"Free (via ALX)","price":0,"period":"forever","features":["Socratic tutoring","Interactive lessons","Critical thinking","ALX programs"]}]'::jsonb),
-- 10. MamaMate
('MamaMate', 'Award-winning AI maternal health app for rural mothers in Tanzania. Offline health advice, mental health monitoring, and local language support. Winner of 2025 AI for Good Innovation Award.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['maternal-health','health-tech','offline-ai','tanzania'], 'https://aiforgood.itu.int/mamamate-and-the-startup-powering-postnatal-support/', '[{"name":"Free","price":0,"period":"forever","features":["Offline health advice","Mental health monitoring","Local language support","Maternal tracking"]}]'::jsonb),
-- 11. Terp 360
('Terp 360', 'Award-winning AI app translating speech into Kenyan Sign Language using 3D avatars and ML. Winner of 2025 Africa Prize for Engineering Innovation. Bridges communication for deaf communities.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['accessibility','sign-language','ai-translation','kenya'], 'https://terp360.com/', '[{"name":"Free","price":0,"period":"forever","features":["Speech to sign language","3D avatar translation","Real-time interpretation","KSL support"]}]'::jsonb),
-- 12. Decide
('Decide', 'Web-based AI data analyst handling problems ChatGPT can''t. Upload Excel/CSV, clean data, generate charts, build dashboards via simple prompts. Export as PDF, Excel, or CSV.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['data-analytics','ai-analyst','dashboards','nigeria'], 'https://trydecide.ai/', '[{"name":"Pay As You Go","price":7,"period":"one-time","features":["20 messages per $7","Data connectors","Premium features","Add credits anytime"]},{"name":"Pro","price":15,"period":"monthly","features":["100 messages/month","Advanced AI model","Data connectors","Priority support"]},{"name":"Team","price":25,"period":"monthly","features":["200 messages/month","Team collaboration","All Pro features","Priority support"]}]'::jsonb),
-- 13. AI Examiner
('AI Examiner', 'AI study assistant built by medical students. Creates practice tests, flashcards, case studies, essays, and oral exam prep from uploaded materials. Trusted by thousands worldwide.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['edtech','study-assistant','exam-prep','nigeria'], 'https://aiexaminer.app/', '[{"name":"Free","price":0,"period":"forever","features":["Limited questions","Basic uploads","MCQ generation","Community access"]},{"name":"Premium","price":0,"period":"monthly","features":["Contact for pricing","Unlimited questions","All question types","AI feedback"]}]'::jsonb),
-- 14. Indigenius AI
('Indigenius AI', 'Non-code voice AI agent platform supporting 30+ languages including African languages. Build and launch conversational AI agents with web and telephony integrations. Formerly CDIAL.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['voice-ai','african-languages','conversational-ai','nigeria'], 'https://indigenius.ai/', '[{"name":"Free","price":0,"period":"forever","features":["5,000 credits","Agent Studio","Web widgets","Command Center"]},{"name":"Flex","price":19,"period":"monthly","features":["15,000 credits","Commercial license","Telephony","Local language STT"]},{"name":"Cool","price":99,"period":"monthly","features":["150,000 credits","Email & Discord support","High quality audio","Everything in Flex"]},{"name":"Prime","price":899,"period":"monthly","features":["1.5M credits","24/7 support","Free phone number","Multi-seat workspace"]}]'::jsonb),
-- 15. ChatATP
('ChatATP', 'AI agent platform making any website interactive for chatting, bookings, and forms. Built by an 18-year-old Nigerian student. The App Store for AI agents on your website.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['chatbot','website-ai','nigeria','automation'], 'https://chat-atp.com/', '[{"name":"Free","price":0,"period":"forever","features":["Basic website AI agent","Limited conversations","Standard responses","Community support"]},{"name":"Pro","price":0,"period":"monthly","features":["Contact for pricing","Unlimited conversations","Custom training","Advanced actions"]}]'::jsonb),
-- 16. Trembi AI
('Trembi AI', 'AI-powered sales automation and CRM. Find leads, engage customers, follow up, and close deals on autopilot with unified WhatsApp, Email, and SMS marketing across Africa.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['sales-automation','crm','lead-generation','africa'], 'https://www.trembi.com/', '[{"name":"Communication (Free)","price":0,"period":"monthly","features":["Pay-per-use messaging","SMS, Email & WhatsApp","1 user","Customer 360 view"]},{"name":"Sales AI","price":0,"period":"monthly","features":["Contact for pricing","AI lead generation","Sales workflows","CRM integrations"]}]'::jsonb),
-- 17. Loubby AI
('Loubby AI', 'Remote workforce OS connecting employers with African talent using AI. Features AI interviewer Dara, recruiting agent Jabari, JD builder, and learning management. 30-day free trial.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['hr-tech','talent-recruiting','ai-hiring','africa'], 'https://www.loubby.ai/', '[{"name":"Free Forever","price":0,"period":"forever","features":["1 job listing","1 seat","Unlimited candidates","Job pipeline"]},{"name":"Growth","price":0,"period":"monthly","features":["Contact for pricing","Unlimited listings","Unlimited seats","AI automations"]},{"name":"Enterprise","price":0,"period":"monthly","features":["Contact sales","Job syndication","Custom permissions","HRIS integrations"]}]'::jsonb),
-- 18. PlantVillage
('PlantVillage', 'AI mobile app by Penn State helping smallholder farmers across Africa detect plant diseases, identify pests, and adapt to climate change. Photo-based instant diagnosis. Used by millions.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['agritech','plant-disease','ai-farming','africa'], 'https://plantvillage.psu.edu/', '[{"name":"Free","price":0,"period":"forever","features":["AI disease detection","Pest identification","Treatment recommendations","Works offline"]}]'::jsonb),
-- 19. Agrix Tech
('Agrix Tech', 'Smart agri-tech platform using AI and blockchain for African agriculture. Buy, store, swap, and sell commodities as digital assets. Real-time market prices for crops.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['agritech','commodity-trading','blockchain','africa'], 'https://agrix.buzz/', '[{"name":"Free","price":0,"period":"forever","features":["Market price tracking","Basic trading","Commodity listings","Community access"]},{"name":"Premium","price":0,"period":"monthly","features":["Contact for pricing","Advanced analytics","Bulk trading","Priority support"]}]'::jsonb),
-- 20. VulaVula
('VulaVula', 'Language technology API by Lelapa AI for transcription, translation, and conversational AI in South African languages including Sesotho, Afrikaans, isiZulu, and SA English.', 'product', 'fce177b9-604d-4e7c-b904-5f18ccf1ec73', 'active', 'b2c3d4e5-6789-abcd-ef01-222222222222', ARRAY['language-ai','african-languages','transcription','south-africa'], 'https://lelapa.ai/products/vulavula/', '[{"name":"Dev Pass","price":9.99,"period":"monthly","features":["1,000 API calls/month","$0.005 per call after","Transcribe & Translate","No rate limit"]},{"name":"SMME Pass","price":49,"period":"monthly","features":["10,000 API calls/month","$0.003 per call after","All services","No rate limit"]},{"name":"Pro Pass","price":499,"period":"monthly","features":["500K API calls/month","$0.003 per call after","All services","No rate limit"]},{"name":"Enterprise","price":0,"period":"monthly","features":["Contact sales","500K+ calls","Lower cost per call","Priority support"]}]'::jsonb);
