
-- Insert marketplace products (AI tools from screenshots)
-- Using user_id of the DIM platform account

INSERT INTO marketplace_listings (user_id, title, description, listing_type, category_id, price, currency, tags, creation_link, is_featured, status, videos, images) VALUES
('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'ElevenLabs', 'ElevenLabs'' AI Audio makes content accessible in any language. Create realistic text-to-speech, voice cloning, and audio content with cutting-edge AI technology. Perfect for creators, developers, and businesses looking to scale audio production.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['AI Audio', 'Text-to-Speech', 'Voice Cloning', 'Content Creation'], 'https://elevenlabs.io', true, 'active', ARRAY['https://www.youtube.com/watch?v=VBxsUjHRxCo'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Unbounce', 'The best landing page builder with AI features for reducing bounce rates and increasing conversions. Build, publish, and optimize landing pages without developers. Smart Traffic AI automatically routes visitors to the best-performing variant.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Landing Pages', 'Marketing', 'AI Optimization', 'Conversion'], 'https://unbounce.com', true, 'active', ARRAY['https://www.youtube.com/watch?v=MNqz31F8B9Q'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'AdCreative.ai', 'Generate conversion-focused ad creatives using artificial intelligence. Create stunning ad designs, social media posts, and marketing visuals in seconds. AI analyzes millions of high-performing ads to generate creatives that convert.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Ad Creatives', 'AI Design', 'Marketing', 'Advertising'], 'https://adcreative.ai', true, 'active', ARRAY['https://www.youtube.com/watch?v=VJpSiRo0tLk'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'ClickUp', 'ClickUp is a versatile project management and productivity platform that brings teams together. Replace scattered tools with one app for tasks, docs, goals, and chat. AI-powered features help automate workflows.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Project Management', 'Productivity', 'Team Collaboration', 'AI'], 'https://clickup.com', true, 'active', ARRAY['https://www.youtube.com/watch?v=lXFSqPghedM'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Murf AI', 'Murf AI is a cloud-based realistic text-to-speech platform offering 120+ natural-sounding AI voices in 20+ languages. Create studio-quality voiceovers for videos, presentations, and e-learning content.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Text-to-Speech', 'Voiceover', 'AI Voice', 'E-Learning'], 'https://murf.ai', false, 'active', ARRAY['https://www.youtube.com/watch?v=UQrSHEGLpMY'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Gamma', 'Gamma is your AI design partner for creating beautiful presentations, documents, and websites. No design skills needed. Just describe what you want and Gamma generates polished, professional content instantly.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Presentations', 'AI Design', 'Documents', 'Content Creation'], 'https://gamma.app', true, 'active', ARRAY['https://www.youtube.com/watch?v=qMITXtRPv8c'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Castmagic', 'Castmagic helps creators turn any form of audio into ready-to-use content. Automatically generate show notes, transcripts, social posts, newsletters, and more from podcasts, meetings, and recordings.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Podcast', 'Content Repurposing', 'Transcription', 'AI'], 'https://castmagic.io', false, 'active', ARRAY['https://www.youtube.com/watch?v=DFP5u0lVNsM'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Looka', 'Create a logo and brand kit you''ll love with Looka''s AI-powered platform. Design professional logos, business cards, social media kits, and complete brand identities in minutes.', 'product', '996a0b4d-0642-4df6-a3ed-bc4344913ed3', 0, 'USD', ARRAY['Logo Design', 'Branding', 'AI Design', 'Business'], 'https://looka.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=VxKOd2X08TY'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'SaneBox', 'SaneBox is the leading AI email productivity tool that cleans up your inbox automatically. It learns your email habits to prioritize important messages and snooze the rest.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Email', 'Productivity', 'AI', 'Inbox Management'], 'https://sanebox.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=gLRFPepL7cs'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Brand24', 'Discover the power of media monitoring with Brand24. Track online mentions across social media, news, blogs, and forums. Get instant access to AI-powered sentiment analysis and real-time alerts.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Social Listening', 'Media Monitoring', 'Analytics', 'Brand Management'], 'https://brand24.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=Jcg5x9GSPOY'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'GetResponse', 'GetResponse offers all-in-one marketing software for email marketing, automation, landing pages, and webinars. Grow your audience and drive sales with AI-powered marketing tools.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Email Marketing', 'Automation', 'Landing Pages', 'Webinars'], 'https://getresponse.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=nL-YtGjOiRU'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Motion', 'AI-powered productivity app that auto-schedules your tasks, meetings, and projects. Motion uses AI to build the perfect daily plan, ensuring you focus on what matters most.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Productivity', 'AI Scheduling', 'Task Management', 'Calendar'], 'https://usemotion.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=kLW92tNxIro'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'MeetGeek', 'MeetGeek is an AI-powered meeting automation platform that records, transcribes, and summarizes your meetings. Never miss important action items and insights from your conversations.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Meeting AI', 'Transcription', 'Productivity', 'Automation'], 'https://meetgeek.ai', false, 'active', ARRAY['https://www.youtube.com/watch?v=8KnwjFYqDMc'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Lindy', 'Lindy is a no-code workflow automation tool for AI agents. Build custom AI assistants that handle emails, schedule meetings, manage CRM, and automate repetitive tasks without coding.', 'product', 'd7a33383-82a4-48a4-be13-5466283da06e', 0, 'USD', ARRAY['AI Agents', 'Automation', 'No-Code', 'Workflow'], 'https://lindy.ai', true, 'active', ARRAY['https://www.youtube.com/watch?v=MHB_qna4gHY'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Reclaim.ai', '#1 AI calendar that automatically protects focus time, schedules habits, and optimizes your schedule. Reclaim uses AI to defend your time and boost productivity across teams.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Calendar', 'AI Scheduling', 'Productivity', 'Time Management'], 'https://reclaim.ai', false, 'active', ARRAY['https://www.youtube.com/watch?v=aY3Z54u2kpE'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Seamless.AI', 'Seamless.AI helps sales teams maximize revenue and increase sales efficiency. Find verified emails, phone numbers, and account insights for your ideal prospects using real-time AI search.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Sales Intelligence', 'Lead Generation', 'B2B', 'Prospecting'], 'https://seamless.ai', false, 'active', ARRAY['https://www.youtube.com/watch?v=I4SQxF0E0oA'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'SleekFlow', 'SleekFlow is the AI-powered Omnichannel Conversation Suite for customer engagement. Unify WhatsApp, Instagram, Facebook Messenger, and more into one platform with AI-driven automation.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Omnichannel', 'Customer Engagement', 'WhatsApp', 'AI Chat'], 'https://sleekflow.io', false, 'active', ARRAY['https://www.youtube.com/watch?v=JgIWNlIFaSg'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Lusha', 'Lusha''s intelligent go-to-market platform brings you the B2B data and insights you need. Find accurate contact and company data for prospecting, enrich your CRM, and close deals faster.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['B2B Data', 'Sales Intelligence', 'CRM', 'Prospecting'], 'https://lusha.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=x2SaF6W7nQI'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Browse AI', 'Maximize your affiliate impact with Browse AI: a top SaaS tool for web scraping and data extraction. Train AI robots to monitor and extract data from any website without coding.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Web Scraping', 'Data Extraction', 'Automation', 'No-Code'], 'https://browse.ai', false, 'active', ARRAY['https://www.youtube.com/watch?v=IhIeJqtSins'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Tidio', 'Grow faster with AI-powered customer service. Tidio unifies live chat, AI chatbots, and helpdesk tools to help businesses provide exceptional customer support and boost sales.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Customer Service', 'AI Chatbot', 'Live Chat', 'Helpdesk'], 'https://tidio.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=8KnwjFYqDMc'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Flowith', 'Flowith (#3 of the Month on Product Hunt) is redefining AI interaction with a canvas-based interface. Think, create, and build with AI in a visual, node-based workspace.', 'product', 'd7a33383-82a4-48a4-be13-5466283da06e', 0, 'USD', ARRAY['AI Canvas', 'Creative AI', 'No-Code', 'Productivity'], 'https://flowith.io', false, 'active', ARRAY['https://www.youtube.com/watch?v=kG10p5V3vb0'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'MindStudio', 'Rapidly build AI agents with MindStudio''s flexible no-code platform. Create custom AI applications for any use case from customer support to content creation without writing code.', 'product', 'd7a33383-82a4-48a4-be13-5466283da06e', 0, 'USD', ARRAY['AI Agents', 'No-Code', 'AI Development', 'Custom AI'], 'https://mindstudio.ai', false, 'active', ARRAY['https://www.youtube.com/watch?v=1h5OPgE7tXI'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Synthflow AI', 'Synthflow is a no-code voice AI agent platform that lets businesses create human-like phone agents. Handle inbound and outbound calls with AI that sounds natural and resolves issues autonomously.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Voice AI', 'Phone Agent', 'No-Code', 'Customer Service'], 'https://synthflow.ai', true, 'active', ARRAY['https://www.youtube.com/watch?v=d-taPTN2v-A'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Recomaze AI', 'Recomaze turns any store into an AI Sales Agent. Agencies and merchants use Recomaze to boost conversions with personalized product recommendations and AI-powered shopping assistance.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['E-Commerce', 'AI Sales', 'Product Recommendations', 'Shopify'], 'https://recomaze.com', false, 'active', '{}', '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Pinecone', 'Pinecone is the leading vector database for building accurate, fast, and scalable AI applications. Store and search through billions of embeddings for semantic search, recommendations, and RAG.', 'product', 'd7a33383-82a4-48a4-be13-5466283da06e', 0, 'USD', ARRAY['Vector Database', 'AI Infrastructure', 'Search', 'RAG'], 'https://pinecone.io', false, 'active', ARRAY['https://www.youtube.com/watch?v=jGNee00OIGU'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Databox', 'Databox is modern BI software trusted by 20,000 scaling teams. Connect all your data sources, build custom dashboards, and get AI-powered insights to make data-driven decisions.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Business Intelligence', 'Analytics', 'Dashboards', 'Reporting'], 'https://databox.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=Rf-7QZBE-bA'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Vista Social', 'Vista Social is a modern social media management platform with AI-powered scheduling, analytics, and engagement tools. Manage all your social channels from one dashboard.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Social Media', 'Marketing', 'Scheduling', 'Analytics'], 'https://vistasocial.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=0HBFP5q8bBw'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Prezi', 'Prezi is an AI presentation tool that helps you stand out with dynamic, visually engaging presentations. Create interactive content that moves with your story for maximum audience impact.', 'product', '996a0b4d-0642-4df6-a3ed-bc4344913ed3', 0, 'USD', ARRAY['Presentations', 'AI Design', 'Visual Content', 'Marketing'], 'https://prezi.com', false, 'active', ARRAY['https://www.youtube.com/watch?v=Yev5_dnOJsQ'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Turbotic', 'Turbotic Automation AI is an AI-powered no-code automation platform that helps businesses streamline operations. Build intelligent workflows and automate repetitive tasks effortlessly.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Automation', 'No-Code', 'AI Workflows', 'Business'], 'https://turbotic.com', false, 'active', '{}', '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Descript', 'Descript is an AI-powered tool for creating and editing video and audio content. Edit media as easily as editing a document with transcription-based editing, screen recording, and AI tools.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Video Editing', 'Audio Editing', 'AI', 'Content Creation'], 'https://descript.com', true, 'active', ARRAY['https://www.youtube.com/watch?v=Bi49MOPHIbo'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Reply.io', 'Reply is an AI Sales Engagement platform combining email, LinkedIn, calls, and SMS outreach. Automate personalized multi-channel sequences to book more meetings and close more deals.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Sales Engagement', 'Email Outreach', 'LinkedIn', 'Automation'], 'https://reply.io', false, 'active', ARRAY['https://www.youtube.com/watch?v=b2TP3g6eLyo'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'KrispCall', 'KrispCall is an AI-driven cloud phone solution that unifies calls, SMS, and voicemail across 100+ countries. Perfect for remote teams, sales, and customer support.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Cloud Phone', 'VoIP', 'Communications', 'AI'], 'https://krispcall.com', false, 'active', '{}', '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Hume AI', 'Hume is the empathic AI company. While other voice AI just talks, Hume understands emotions and responds with genuine empathy. Build emotionally intelligent AI applications.', 'product', 'd7a33383-82a4-48a4-be13-5466283da06e', 0, 'USD', ARRAY['Empathic AI', 'Voice AI', 'Emotion Recognition', 'API'], 'https://hume.ai', false, 'active', ARRAY['https://www.youtube.com/watch?v=M2bFaAHWuVw'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Logome.ai', 'Create a logo and brand kit you''ll love with Logome''s AI-powered logo maker. Generate professional logos in seconds and build a complete brand identity.', 'product', '996a0b4d-0642-4df6-a3ed-bc4344913ed3', 0, 'USD', ARRAY['Logo Design', 'AI Design', 'Branding', 'Business'], 'https://logome.ai', false, 'active', '{}', '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'BLACKBOX AI', 'AI-powered coding assistant that helps developers write, review, and debug code faster. Get intelligent code completions, explanations, and automated testing across any programming language.', 'product', 'd7a33383-82a4-48a4-be13-5466283da06e', 0, 'USD', ARRAY['AI Coding', 'Developer Tools', 'Code Generation', 'Productivity'], 'https://blackbox.ai', false, 'active', ARRAY['https://www.youtube.com/watch?v=1XrP_iR9VMs'], '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Adwisely', 'Adwisely is an AI-powered Shopify application designed to automate Facebook, Instagram, and Google ads. Maximize your ROAS with intelligent ad optimization.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['E-Commerce Ads', 'Shopify', 'AI Advertising', 'ROAS'], 'https://adwisely.com', false, 'active', '{}', '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Tiki', 'Tiki unlocks value for businesses by bringing new data streams. Turn user data into insights with privacy-first technology and transparent data exchange.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Data Privacy', 'Data Exchange', 'Analytics', 'Business Intelligence'], 'https://mytiki.com', false, 'active', '{}', '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'Pilim', 'Pilim is an AI-powered business management platform that streamlines operations, automates workflows, and provides intelligent insights to help businesses scale efficiently.', 'product', '44181a81-cd7f-4bbb-9cdc-190123ee41d6', 0, 'USD', ARRAY['Business Management', 'AI Automation', 'Operations', 'Productivity'], 'https://pilim.io', false, 'active', '{}', '{}'),

('04813cca-d8cf-4a63-b1f5-02b40d99d157', 'soona', 'soona is a platform built for brands to scale creative content production. Get professional product photos and videos with AI-powered editing and virtual studio technology.', 'service', 'd537cad3-7722-4695-a931-d179b1ff14c0', 0, 'USD', ARRAY['Product Photography', 'Content Creation', 'E-Commerce', 'Creative'], 'https://soona.co', false, 'active', ARRAY['https://www.youtube.com/watch?v=5JFjvfhfnQU'], '{}');
